---
fixtures:
  repositories:
    compliance:  'https://github.com/trevor-vaughan/pupmod-compliance'
    simplib:     'https://github.com/simp/pupmod-simp-simplib.git'
    iptables:    'https://github.com/simp/pupmod-simp-iptables.git'
    rsync:       'https://github.com/simp/pupmod-simp-rsync.git'
    stdlib:      'https://github.com/simp/puppetlabs-stdlib.git'
    xinetd:      'https://github.com/simp/pupmod-simp-xinetd.git'
  symlinks:
    tftpboot: "#{source_dir}"
