---
fixtures:
  repositories:
    common  : "git://github.com/simp/pupmod-simp-common"
    iptables: "git://github.com/simp/pupmod-simp-iptables"
    rsync   : "git://github.com/simp/pupmod-simp-rsync"
    stdlib  : "git://github.com/simp/puppetlabs-stdlib"
    xinetd  : "git://github.com/simp/pupmod-simp-xinetd"
  symlinks:
    tftpboot: "#{source_dir}"
